vimdiff /tmp/causify-ai/tutorials/tmp.base/DATA605_README.md DATA605/README.md
vimdiff /dev/null DATA605/tutorial_template/README.md
vimdiff /dev/null DATA605/tutorial_template/docker_causify_style/.DS_Store
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/Dockerfile
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/bashrc
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/docker_bash.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/docker_build.log
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/docker_build.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/docker_build.version.log
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/docker_clean.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/docker_exec.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/docker_push.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/etc_sudoers
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/install_jupyter_extensions.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/run_jupyter.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/Dockerfile
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/bashrc
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/docker_bash.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/docker_build.log
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/docker_build.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/docker_build.version.log
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/docker_clean.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/docker_exec.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/docker_push.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/etc_sudoers
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/install_jupyter_extensions.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/run_jupyter.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/tmp.build/version.sh
vimdiff /dev/null DATA605/tutorial_template/docker_data605_style/version.sh
vimdiff /dev/null docker_common/bashrc
vimdiff /dev/null docker_common/docker_bash.sh
vimdiff /dev/null docker_common/docker_build.sh
vimdiff /dev/null docker_common/docker_clean.sh
vimdiff /dev/null docker_common/docker_cmd.sh
vimdiff /dev/null docker_common/docker_exec.sh
vimdiff /dev/null docker_common/docker_jupyter.sh
vimdiff /dev/null docker_common/docker_push.sh
vimdiff /dev/null docker_common/etc_sudoers
vimdiff /dev/null docker_common/install_jupyter_extensions.sh
vimdiff /dev/null docker_common/run_jupyter.sh
vimdiff /dev/null docker_common/utils.sh
vimdiff /dev/null docker_common/version.sh
vimdiff /dev/null helpers_root
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_.dockerignore /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github___init__.py /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_changelog.txt /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_conftest.py /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_dev_scripts_tutorial_github_thin_client_setenv.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops___init__.py /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_compose___init__.py /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_create_users.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_dev.Dockerfile /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_dockerignore.dev /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_dockerignore.prod /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_etc_sudoers /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_fstab /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_install_cprofile.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_install_dind.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_install_os_packages.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_install_publishing_tools.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_install_python_packages.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_pip_list.txt /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_poetry.lock /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_poetry.toml /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_prod.Dockerfile /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_pyproject.python_data_stack.toml /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_pyproject.toml /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_update_os.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_build_utils.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_run_bashrc /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_run_docker_setenv.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_run_entrypoint.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_run_run_jupyter_server.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_docker_run_test_setup.sh /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_devops_env_default.env /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_github.API.ipynb /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_github.API.md /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_github.API.py /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_github.example.ipynb /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_github.example.md /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_github.example.py /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_github_api_tutorial.ipynb /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_github_utils.py /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_invoke.yaml /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_pytest.ini /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_repo_config.yaml /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_tasks.py /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_github_utils.py /dev/null
vimdiff /dev/null tutorial_github_causify_style/README.md
vimdiff /dev/null tutorial_github_causify_style/__init__.py
vimdiff /dev/null tutorial_github_causify_style/changelog.txt
vimdiff /dev/null tutorial_github_causify_style/devops/docker_build/dev.Dockerfile
vimdiff /dev/null tutorial_github_causify_style/devops/docker_build/install_os_packages.sh
vimdiff /dev/null tutorial_github_causify_style/devops/docker_build/pip_list.txt
vimdiff /dev/null tutorial_github_causify_style/devops/docker_build/poetry.lock
vimdiff /dev/null tutorial_github_causify_style/github.API.ipynb
vimdiff /dev/null tutorial_github_causify_style/repo_config.yaml
vimdiff /dev/null tutorial_github_data605_style/Dockerfile
vimdiff /dev/null tutorial_github_data605_style/README.md
vimdiff /dev/null tutorial_github_data605_style/bashrc
vimdiff /dev/null tutorial_github_data605_style/docker_bash.sh
vimdiff /dev/null tutorial_github_data605_style/docker_build.sh
vimdiff /dev/null tutorial_github_data605_style/docker_build.version.log
vimdiff /dev/null tutorial_github_data605_style/docker_clean.sh
vimdiff /dev/null tutorial_github_data605_style/docker_exec.sh
vimdiff /dev/null tutorial_github_data605_style/docker_jupyter.sh
vimdiff /dev/null tutorial_github_data605_style/docker_name.sh
vimdiff /dev/null tutorial_github_data605_style/docker_push.sh
vimdiff /dev/null tutorial_github_data605_style/etc_sudoers
vimdiff /dev/null tutorial_github_data605_style/github.API.md
vimdiff /dev/null tutorial_github_data605_style/github.example.ipynb
vimdiff /dev/null tutorial_github_data605_style/github.example.md
vimdiff /dev/null tutorial_github_data605_style/github_utils.py
vimdiff /dev/null tutorial_github_data605_style/install_jupyter_extensions.sh
vimdiff /dev/null tutorial_github_data605_style/install_project_packages.sh
vimdiff /dev/null tutorial_github_data605_style/requirements.txt
vimdiff /dev/null tutorial_github_data605_style/run_jupyter.sh
vimdiff /dev/null tutorial_github_data605_style/version.sh
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_langchain_README.md tutorial_langchain/README.md
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_template_README.md /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_template___init__.py /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_template_template.API.ipynb /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_template_template.API.md /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_template_template.API.py /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_template_template.example.ipynb /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_template_template.example.md /dev/null
vimdiff /tmp/causify-ai/tutorials/tmp.base/tutorial_template_template.example.py /dev/null