apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-fetcher-config
data:
  api_url: "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd&include_market_cap=true&include_24hr_vol=true&include_24hr_change=true"