apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bitcoin-price-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2025-04-26T11:41:42.489122',
    pipelines.kubeflow.org/pipeline_spec: '{"name": "Bitcoin price pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: bitcoin-price-pipeline
  templates:
  - name: bitcoin-price-pipeline
    dag:
      tasks:
      - {name: fetch-bitcoin-price, template: fetch-bitcoin-price}
  - name: fetch-bitcoin-price
    container:
      command: [python, fetch_bitcoin_price.py]
      env:
      - {name: DB_USER, value: postgres}
      - {name: DB_PASSWORD, value: testpass}
      - {name: DB_HOST, value: host.docker.internal}
      - {name: DB_PORT, value: '5432'}
      - {name: DB_NAME, value: bitcoin_db}
      - {name: COINGECKO_API_KEY, value: CG-KufNKPvFrCUCFUWHxW6yyXTM}
      image: bitcoin-fetcher:v1
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
