FROM python:3.12-slim

WORKDIR /app

# Install dependencies first for Docker layer caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy your code
COPY . .

# If you have a utilfunctions directory, copy it as well
# COPY utilfunctions ./utilfunctions

CMD ["python", "load_backup_to_db.py"]
