stages:
  fetch_price:
    cmd: python -c "from src.data_ingestion import record_price; record_price()"
    deps:
    - src/data_ingestion.py
    outs:
    - data/bitcoin_prices.csv
  preprocess_and_plot:
    cmd: python -c "from src.preprocess_eda import preprocess, plot_data; df = preprocess();
      plot_data(df)"
    deps:
    - data/bitcoin_prices.csv
    - src/preprocess_eda.py
    outs:
    - Output/bitcoin_price_plot.png
    - data/cleaned_bitcoin.csv
