authors:
  gpsaggese:
    name: GP Saggese
    description: Chief Technology Officer
    avatar: https://avatars.githubusercontent.com/u/33238329
    url: https://github.com/gpsaggese
  jsherlock:
    name: Joel Sherlock
    description: Chief Executive Officer
    avatar: https://blog.causify.ai/img/authors/joel.jpg
    url: 
  psmith:
    name: Paul Smith
    description: Chief Scientist
    avatar: https://avatars.githubusercontent.com/u/7649219?v=4
    url: https://github.com/gitpaulsmith
  shaunakdhande:
    name: Shaunak Dhande
    description: ML Engineer
    avatar: https://blog.causify.ai/img/authors/shaunak.jpeg
    url: https://github.com/shaunak01
  heanhsok:
    name: Hean Sok
    description: ML Engineer
    avatar: https://blog.causify.ai/img/authors/heanhsok.jpg
    url: https://github.com/heanhsok
  dremdem:
    name: Vlad Demedetskiy
    avatar: https://blog.causify.ai/img/authors/vlad.png
    url: https://github.com/dremdem
  Shayawnn:
    name: Shayan Ghasemnezhad
    avatar: https://blog.causify.ai/img/authors/shayan.jpg
    url: https://github.com/Shayawnn
  samarth9008:
    name: Samarth KaPatel
    avatar: https://blog.causify.ai/img/authors/samarth.png
    url: https://github.com/samarth9008
