version: '3'
services:
  base_app:
    cap_add:
      - SYS_ADMIN
    environment:
      - AM_ENABLE_DIND=1
      - AM_FORCE_TEST_FAIL=$AM_FORCE_TEST_FAIL
      - AM_HOST_NAME=dev1
      - AM_HOST_OS_NAME=Linux
      - AM_HOST_USER_NAME=krishnap
      - AM_HOST_VERSION=5.15.0-1072-aws
      - AM_REPO_CONFIG_CHECK=True
      - AM_REPO_CONFIG_PATH=
      - CK_AWS_ACCESS_KEY_ID=$CK_AWS_ACCESS_KEY_ID
      - CK_AWS_DEFAULT_REGION=$CK_AWS_DEFAULT_REGION
      - CK_AWS_PROFILE=$CK_AWS_PROFILE
      - CK_AWS_S3_BUCKET=$CK_AWS_S3_BUCKET
      - CK_AWS_SECRET_ACCESS_KEY=$CK_AWS_SECRET_ACCESS_KEY
      - CK_ECR_BASE_PATH=$CK_ECR_BASE_PATH
      - CSFY_GIT_ROOT_PATH=/app
      - CSFY_HELPERS_ROOT_PATH=/app/helpers_root
      - CSFY_IS_SUPER_REPO=1
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - CK_TELEGRAM_TOKEN=$CK_TELEGRAM_TOKEN
      - GH_ACTION_ACCESS_TOKEN=$GH_ACTION_ACCESS_TOKEN
      - GH_TOKEN=$GH_ACTION_ACCESS_TOKEN
      - CSFY_CI=$CSFY_CI
    image: ${IMAGE}
    restart: 'no'
    volumes:
      - ~/.aws:/home/.aws
      - ~/.config/gspread_pandas/:/home/.config/gspread_pandas/
      - ~/.config/gh:/home/.config/gh
      - /data/shared:/shared_data
      - /data/shared2:/shared_data2
    privileged: true
  app:
    extends: base_app
    volumes:
      - /data/krishnap/src/tutorials:/app
    working_dir: /app/tutorial_asana
  linter:
    extends: base_app
    volumes:
      - /data/krishnap/src/tutorials/tutorial_asana:/src
      - ../../:/app
    working_dir: /src
    environment:
      - MYPYPATH
  jupyter_server:
    command: devops/docker_run/run_jupyter_server.sh
    environment:
      - PORT=${PORT}
    extends: app
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - ${PORT}:${PORT}
  jupyter_server_test:
    command: jupyter notebook -h 2>&1 >/dev/null
    environment:
      - PORT=${PORT}
    extends: app
    network_mode: ${NETWORK_MODE:-bridge}
    ports:
      - ${PORT}:${PORT}
