import pandas as pd
from config.clickhouse_client import client
import plotly.graph_objects as go
from plotly.subplots import make_subplots


def fetch_dashboard_specs():
    """
    Retrieve dashboard specifications.

    Returns:
        List of (dashboard_name, chart_title, SQL_query) tuples.
    """
    sql = """
      SELECT dashboard, title, query
      FROM system.dashboards
      ORDER BY dashboard, title
    """
    return client.command(sql)


def build_dynamic_dashboard(name: str):
    """
    Build a dynamic Plotly dashboard for the given dashboard name.
    Each chart in the dashboard is generated by executing the associated SQL query.

    Args:
        name: Dashboard name.

    Returns:
        A multi-row Plotly figure with one subplot per chart.
    """
    specs = [spec for spec in fetch_dashboard_specs() if spec[0] == name]
    if not specs:
        raise KeyError(f"No dashboard named {name!r}")

    n = len(specs)
    fig = make_subplots(
        rows=n,
        cols=1,
        subplot_titles=[title for _, title, _ in specs],
        vertical_spacing=0.08,
    )

    for i, (_, title, query) in enumerate(specs, start=1):
        try:
            data = client.query_df(query)
            if data.empty:
                continue
            if len(data.columns) < 2:
                raise ValueError(
                    f"Query for {title} must return two columns: time, value"
                )
            df = pd.DataFrame(data)
            df.columns = ["t", "v"]
            fig.add_trace(
                go.Scatter(x=df["t"], y=df["v"], mode="lines", name=title), row=i, col=1
            )
        except Exception as e:
            fig.add_annotation(
                text=f"Error loading '{title}': {e}",
                row=i,
                col=1,
                font=dict(color="red"),
                showarrow=False,
            )

    fig.update_layout(
        height=300 * n,
        title_text=f"Dashboard: {name}",
        template="plotly",
        # template="plotly_dark",
    )
    return fig
