# -*- coding: utf-8 -*-
"""Prefect main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ii1Ulz53iF4kB0_A8BnwlqV340tyOHih
"""

# Install prefect
from prefect import flow, task, get_run_logger
from prefect.artifacts import create_markdown_artifact, create_image_artifact
import requests
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine
import io
import os


@task
def fetch_bitcoin_price():
    logger = get_run_logger()
    url = "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd"
    response = requests.get(url)
    data = response.json()

    if response.status_code != 200:
        logger.error(f"Error fetching data: {response.status_code}")
        return None
    if 'bitcoin' not in data or 'usd' not in data.get('bitcoin'):
        logger.error("Error: Bitcoin price not found in response.")
        return None

    logger.info(f"📈 Bitcoin Price Fetched: ${data['bitcoin']['usd']}")
    return {
        "price": data["bitcoin"]["usd"],
        "timestamp": response.headers.get("Date")
    }


@task
def validate_data(data):
    if data is None:
        get_run_logger().warning("No data to validate.")
        return None
    assert "price" in data and data["price"] > 0, "Price data is invalid"
    return data


@task
def log_to_prefect_artifact(data):
    if data is None:
        get_run_logger().warning("No data to log to artifact.")
        return
    markdown = f"""
### 📊 Bitcoin Price Log

| Timestamp | Price (USD) |
|-----------|-------------|
| {data['timestamp']} | ${data['price']} |
"""
    create_markdown_artifact(key="bitcoin-price-log", markdown=markdown)


@task
def analyze_data_single_point(data):
    if data is None:
        get_run_logger().warning("No data to analyze.")
        return None
    price = data["price"]
    timestamp = data["timestamp"]
    markdown = f"""
### 📈 Bitcoin Price Update

| Timestamp | Price (USD) |
|-----------|-------------|
| {timestamp} | ${price} |

✅ Data shown here was pulled and displayed in this run.
"""
    create_markdown_artifact(key="bitcoin-price-artifact", markdown=markdown)
    return price


@task
def visualize_price(data):
    import matplotlib.pyplot as plt
    import io
    import base64
    from prefect.artifacts import create_markdown_artifact

    logger = get_run_logger()

    if data is None:
        logger.warning("No data to plot.")
        return

    # Plot the data
    fig, ax = plt.subplots()
    ax.plot([1], [data["price"]], marker='o', label="Current Price")
    ax.set_title("Bitcoin Price Snapshot")
    ax.set_ylabel("Price (USD)")
    ax.legend()

    # Save the image to an in-memory buffer
    buf = io.BytesIO()
    plt.savefig(buf, format="png")
    buf.seek(0)

    # Encode the image to base64 for embedding
    encoded = base64.b64encode(buf.read()).decode("utf-8")
    image_md = f"### Bitcoin Price Chart\n\n![plot](data:image/png;base64,{encoded})"

    create_markdown_artifact(
        key="bitcoin-price-image-markdown",
        markdown=image_md
    )

    logger.info("✅ Bitcoin price chart uploaded as markdown artifact.")



@task
def save_to_postgres(data):
    from sqlalchemy import create_engine
    import pandas as pd
    logger = get_run_logger()

    if data is None:
        logger.warning("No data to save.")
        return

    # Use Docker-based PostgreSQL connection
    POSTGRES_URL = "postgresql://sahithi:secret123@localhost:5432/bitcoin_etl"

    df = pd.DataFrame([data])
    try:
        engine = create_engine(POSTGRES_URL)
        df.to_sql("prices", con=engine, if_exists="append", index=False)
        logger.info("✅ Data saved to PostgreSQL (Docker).")
    except Exception as e:
        logger.error(f"❌ Failed to save to PostgreSQL: {e}")



@task
def detect_trend():
    engine = create_engine("sqlite:///bitcoin_prices.db")
    try:
        df = pd.read_sql("SELECT * FROM prices ORDER BY timestamp DESC LIMIT 2", con=engine)
    except Exception as e:
        get_run_logger().warning(f"Could not read from DB: {e}")
        return

    if len(df) < 2:
        print("ℹ️ Not enough data for trend detection.")
        return

    pct_change = (df.iloc[0]['price'] - df.iloc[1]['price']) / df.iloc[1]['price']
    if pct_change > 0.05:
        print("🚨 Spike detected: > 5% increase!")
    elif pct_change < -0.05:
        print("📉 Drop detected: > 5% decrease!")
    else:
        print("✅ No major spike or drop detected.")


@flow
def bitcoin_etl_flow():
    data = fetch_bitcoin_price()
    if data:
        data = validate_data(data)
        if data:
            log_to_prefect_artifact(data)
            analyze_data_single_point(data)
            visualize_price(data)
            save_to_postgres(data)
            detect_trend()
        else:
            get_run_logger().error("Data validation failed. Skipping remaining tasks.")
    else:
        get_run_logger().error("Failed to fetch data. Skipping all tasks.")


if __name__ == "__main__":
    bitcoin_etl_flow()