FROM jupyter/datascience-notebook:latest

USER root

# Install Java + OpenRefine
RUN apt-get update && \
    apt-get install -y openjdk-17-jre-headless wget && \
    wget https://github.com/OpenRefine/OpenRefine/releases/download/3.7.6/openrefine-linux-3.7.6.tar.gz && \
    tar -xzf openrefine-linux-3.7.6.tar.gz -C /opt && \
    mv /opt/openrefine-* /opt/openrefine && \
    chmod +x /opt/openrefine/refine && \
    rm openrefine-linux-3.7.6.tar.gz && \
    ln -s /opt/openrefine-3.7.6/refine /usr/local/bin/refine && \
    chmod +x /opt/openrefine-3.7.6/refine

# Install Python client
RUN pip install requests pandas matplotlib git+https://github.com/PaulMakepeace/refine-client-py.git
