{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0e8de4a6-7388-43af-b0be-c170379e3291",
   "metadata": {},
   "outputs": [],
   "source": [
    "# bitcoin_utils.py\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import requests\n",
    "from datetime import datetime, timedelta\n",
    "from sklearn.linear_model import LassoCV\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from econml.dml import LinearDML\n",
    "from econml.dr import DRLearner\n",
    "from pytrends.request import TrendReq\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# -----------------------------\n",
    "# 1. Fetch real-time Bitcoin price (last 90 days)\n",
    "# -----------------------------\n",
    "def fetch_bitcoin_price():\n",
    "    url = \"https://api.coingecko.com/api/v3/coins/bitcoin/market_chart\"\n",
    "    params = {\n",
    "        \"vs_currency\": \"usd\",\n",
    "        \"days\": \"90\",  # fetch last 90 days\n",
    "        \"interval\": \"daily\"\n",
    "    }\n",
    "    response = requests.get(url, params=params)\n",
    "    data = response.json()\n",
    "    \n",
    "    prices = data['prices']  # [timestamp, price]\n",
    "    df = pd.DataFrame(prices, columns=[\"timestamp\", \"price\"])\n",
    "    df['date'] = pd.to_datetime(df['timestamp'], unit='ms').dt.date\n",
    "    df = df.groupby(\"date\").mean().reset_index()\n",
    "    return df[['date', 'price']]\n",
    "\n",
    "# -----------------------------\n",
    "# 2. Fetch Google Trends data for \"Bitcoin\"\n",
    "# -----------------------------\n",
    "def fetch_google_trends():\n",
    "    pytrends = TrendReq(hl='en-US', tz=360)\n",
    "    today = datetime.today()\n",
    "    start_date = (today - timedelta(days=90)).strftime('%Y-%m-%d')\n",
    "    end_date = today.strftime('%Y-%m-%d')\n",
    "    \n",
    "    kw_list = [\"Bitcoin\"]\n",
    "    pytrends.build_payload(kw_list, cat=0, timeframe='today 3-m', geo='', gprop='')\n",
    "    df_trend = pytrends.interest_over_time().reset_index()\n",
    "    df_trend['date'] = df_trend['date'].dt.date\n",
    "    return df_trend[['date', 'Bitcoin']]\n",
    "\n",
    "# -----------------------------\n",
    "# 3. Merge Bitcoin price and Google Trends\n",
    "# -----------------------------\n",
    "def prepare_dataset():\n",
    "    df_price = fetch_bitcoin_price()\n",
    "    df_trend = fetch_google_trends()\n",
    "    \n",
    "    df = pd.merge(df_price, df_trend, on='date')\n",
    "    df.rename(columns={'Bitcoin': 'trend'}, inplace=True)\n",
    "    df.dropna(inplace=True)\n",
    "    df['price_change'] = df['price'].pct_change().fillna(0)\n",
    "    \n",
    "    # Scale features\n",
    "    scaler = StandardScaler()\n",
    "    df[['trend_scaled']] = scaler.fit_transform(df[['trend']])\n",
    "    \n",
    "    return df\n",
    "\n",
    "# -----------------------------\n",
    "# 4. Train DoubleML model\n",
    "# -----------------------------\n",
    "def train_dml_model(df):\n",
    "    X = df[['trend_scaled']]\n",
    "    T = df['trend_scaled']\n",
    "    Y = df['price_change']\n",
    "\n",
    "    model_y = RandomForestRegressor(n_estimators=100, random_state=0)\n",
    "    model_t = LassoCV(cv=5)\n",
    "\n",
    "    dml = LinearDML(model_y=model_y, model_t=model_t, random_state=0)\n",
    "    dml.fit(Y, T, X=X)\n",
    "    treatment_effect = dml.effect(X)\n",
    "    \n",
    "    return treatment_effect, dml\n",
    "\n",
    "# -----------------------------\n",
    "# 5. Train Doubly Robust model\n",
    "# -----------------------------\n",
    "def train_dr_model(df):\n",
    "    X = df[['trend_scaled']]\n",
    "    T = df['trend_scaled']\n",
    "    Y = df['price_change']\n",
    "\n",
    "    model_y = RandomForestRegressor(n_estimators=100, random_state=0)\n",
    "    model_t = LassoCV(cv=5)\n",
    "\n",
    "    dr = DRLearner(model_regression=model_y, model_propensity=model_t)\n",
    "    dr.fit(Y, T, X=X)\n",
    "    treatment_effect = dr.effect(X)\n",
    "\n",
    "    return treatment_effect, dr\n",
    "\n",
    "# -----------------------------\n",
    "# 6. Plot treatment effect\n",
    "# -----------------------------\n",
    "def plot_effects(df, effect, title=\"Estimated Causal Effect\"):\n",
    "    plt.figure(figsize=(10, 4))\n",
    "    plt.plot(df['date'], effect, label='Estimated Effect')\n",
    "    plt.title(title)\n",
    "    plt.xlabel(\"Date\")\n",
    "    plt.ylabel(\"Causal Effect on Return\")\n",
    "    plt.legend()\n",
    "    plt.grid(True)\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
