name: Publish MkDocs
on:
  push:
    branches:
      - master
      - TutorTask598_Publish_causify_blog_from_tutorials_2
  # Run manually.
  workflow_dispatch:
  # Run once a day at 1:00 am UTC even if there are no commits.
  schedule:
    - cron: "0 1 */1 * *"
permissions:
  # This is required for requesting the OIDC JWT.
  id-token: write
  # This is required for actions/checkout.
  contents: read
  # This is required for pulling the Docker image from GHCR.
  packages: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs build
        working-directory: ./blog
      - run: ls -la
      - run: ls -la ./blog
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ vars.GH_ACTION_AWS_ROLE_ARN }}
          role-session-name: ${{ vars.GH_ACTION_AWS_SESSION_NAME }}
          aws-region: ${{ vars.CSFY_AWS_DEFAULT_REGION }}
      - name: Publish files to S3
        run: |
          aws s3 sync ./blog s3://causify-blog
